### ISSUE TITLE
2024 update

### ISSUE THREAD

**Issue by markzakharyan** [democat3457/swerve-lib#11]
Hi, thank you for maintaining this fork of sds swervelib!

I wanted to ask if there were any plans to update this for the 2024 motor libraries and 2024 wpilib?

Thanks!
Mark

**Comment by democat3457** [comment]
yup, working on it!

edit: realized i'm actually waiting on CTRE to release their 2024 update first

**Comment by markzakharyan** [comment]
I think they have it updated (still beta though). i spent a while trying to change the dependencies but jeez they completely rewrote the library with phoenix6 haha

https://software-metadata.revrobotics.com/REVLib-2024.json
https://maven.ctr-electronics.com/release/com/ctre/phoenix6/latest/Phoenix6-frc2024-beta-latest.json

**Comment by democat3457** [comment]
Ok, I just released a beta version that has an updated WPILib and REVLib and the latest beta release of Phoenix
https://github.com/democat3457/swerve-lib/releases/tag/2024.0.1.0

**Comment by hollisms** [comment]
With the upgrade to Pheonix 6 do you think the CANcoder abs mode stuff is resolved?

**Comment by democat3457** [comment]
Looking at the API, it seems so- the getPosition() method now always returns an absolute value, and there's a separate explicit call to get the relative position.

Also, it seems CTRE just made the official release, I'll upgrade to that later today and rerelease.

**Comment by democat3457** [comment]
Alright, I've released an update that upgrades Phoenix 6 to the latest release (2024.1.0) and fixes an issue with the CANcoder angle calculation:
https://github.com/democat3457/swerve-lib/releases/tag/2024.0.2.0

**Comment by markzakharyan** [comment]
awesome, thanks!

**Comment by democat3457** [comment]
With the release of 2024.0.3.1, I think Falcon steering is good now- has anyone tested with NEO steering? Seeing if someone can reproduce issues in [this CD thread](https://www.chiefdelphi.com/t/swerve-drivetrain-not-working/452025?u=democat)

**Comment by markzakharyan** [comment]
We're running the current beta swervelib (wpilib2024) with falcon drive motors and neo steer motors. There haven't been any issues for us yet (everything works as intended) @democat3457

**Comment by democat3457** [comment]
With the release of 2024.1.0.0 on prod, I think swerve-lib is stable enough for this issue to be closed. Thanks for the help, everyone!

**Comment by hollisms** [comment]
Thank you for all of your work supporting swervelib!
