### ISSUE TITLE
One swerve module not aligning

### ISSUE THREAD

**Issue by BrandonBeaver117** [democat3457/swerve-lib#2]
One of our swerve modules no longer aligns with the other modules. The only thing that was changed was switching from the SwerveDriveSpecialties library to yours. Is it necessary to edit this code in order to correctly implement the library?

**Comment by democat3457** [comment]
It shouldn't be, I've gotten that single module alignment issue before and I think we fixed it by turning the robot on and off again a few times to get the motor encoder to sync with the CANcoder (and re-calibrating the offsets just in case something got funky)

**Comment by BrandonBeaver117** [comment]
Ah cool, it worked! Thanks!
