### ISSUE TITLE
Using AnalogEncoders in MkSwerveModuleBuilder

### ISSUE THREAD

**Issue by FRC7447** [democat3457/swerve-lib#6]
Is there a way to utilize AnalogEncoders in MkSwerveModuleBuilder instead of CANCoders for `.withSteerEncoderPort()`

**Comment by democat3457** [comment]
not yet - I can add it, but what units does AbsoluteEncoder#getAbsolutePosition return?

**Comment by clrozeboom** [comment]
Something like this would be great for ThriftyEncoders. We've been using it in our code and YAGSL just added a class based on this as well. https://github.com/FRC5010/FRCLibrary/blob/main/FRC5010Example2023/src/main/java/frc/robot/FRC5010/sensors/AnalogInput5010.java https://github.com/BroncBotz3481/YAGSL-Example/commit/237b86bb5b2999e9bc1e9e7f94be977c2d8ac3f3 It returns units of radians from -PI to PI.

**Comment by FRC7447** [comment]
I see. We actually just decided to switch over to CANCoders due to the nature of AnalogInput utilizing voltages to calculate position and it's compatibility with other libraries as well. Thanks though.
