### ISSUE TITLE
Accessing individual motor controllers

### ISSUE THREAD

**Issue by JamesFriggens** [democat3457/swerve-lib#9]
Hello, thank you from team 3546 for maintaining a swerve library that works with the SDS swerve drive kits. Our team is new to swerve this year and it has been a very smooth process. 

We do have one question, we are all intermediate in skill when it comes to programming and we were wondering if there is a way to access each of the individual motor controllers. Our team wants to change our drive motors to coast mode and after looking through the code it appears they are all set to brake. Our swerve drive occasionally binds up (usually when we are low power) but it is also a preference our driver has.

**Comment by democat3457** [comment]
Yes, there is indeed a way to get the drive and steer motors. Use SwerveModule.getSteerMotor() or getDriveMotor(), depending on what you want- these methods return a WPILib MotorController object which you can then cast to whatever motors you are using.

**Comment by JamesFriggens** [comment]
We got it all working, thanks for the speedy response!
